In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu124


In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [14]:
#vector
vector = torch.tensor([7,7])

In [15]:
vector.ndim

1

In [16]:
#MAtrix
M = torch.tensor([[1,2],
                  [3,4]])
M

tensor([[1, 2],
        [3, 4]])

In [17]:
M.ndim

2

In [18]:
M.shape

torch.Size([2, 2])

In [22]:
#Tensor
T = torch.tensor([[[[1,2,3],
                   [3,6,7],
                   [7,11,9]]]])
T

tensor([[[[ 1,  2,  3],
          [ 3,  6,  7],
          [ 7, 11,  9]]]])

In [23]:
T.ndim

4

In [24]:
T.shape

torch.Size([1, 1, 3, 3])

In [35]:
#Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2090, 0.1312, 0.7102, 0.1624],
        [0.6966, 0.5626, 0.0784, 0.5164],
        [0.0525, 0.1583, 0.7783, 0.9154]])

In [29]:
random_image_tensor = torch.rand(size=(3,224,224))
random_image_tensor.ndim

3

In [30]:
random_image_tensor.shape

torch.Size([3, 224, 224])

In [36]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
ones.dtype

torch.float32

In [42]:
one_to_ten =torch.arange(start =1, end=11, step = 1)

In [44]:
#creating tensors like
one_to_ten.shape

torch.Size([10])

In [45]:
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [56]:
#float32 tensor
float_32_tensor = torch.tensor([2.0,4,6], dtype = None,
                              device= None,
                              requires_grad = False)
float_32_tensor.dtype

torch.float32

In [62]:
float16_tensor = float_32_tensor.type(torch.float16)
float16_tensor

tensor([2., 4., 6.], dtype=torch.float16)

In [63]:
float16_tensor * float_32_tensor

tensor([ 4., 16., 36.])

In [64]:
float16_tensor.device

device(type='cpu')

In [65]:
#Tensor operations
#Addition, subtraction, Multiplication,Division, 
# Matrix multiplication


In [68]:
# create a tensor and add a scalar
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [69]:
tensor * 10

tensor([10, 20, 30])

In [70]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [72]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [83]:
tensor.div(10)

tensor([0.1000, 0.2000, 0.3000])

In [84]:
tensor

tensor([1, 2, 3])

In [85]:
#Matrix Multiplication
tensor.matmul(tensor)

tensor(14)

In [87]:
torch.matmul(tensor,tensor)

tensor(14)

In [90]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [91]:
# Aggregation operations on a tensor


In [103]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [101]:
x.max(), x.min(), x.sum()

(tensor(90), tensor(0), tensor(450))

In [106]:
#torch.mean() doesn't work with long, needs float32 as dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [107]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [110]:
x.argmax(),x.argmin().item()

(tensor(9), 0)

In [111]:
# Reshaping, stacking, squeezing, unsqueezing tensors
# View, return a view on input tensor of certain shape, but keep the same memory as the original tensor
# stacking - combine multiple tensors on top of each other (vstack) or side y side (hstack)
# squeeze - remove all '1' dimensions from a tensor
# unsqueeze add a '1' dimesion to a target tensor
# Permute - return a view of the input tensor in a certain shape

In [121]:
x  = torch.arange(1.,13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [124]:
# add an extra dimension
x_reshaped = x.reshape(3,2,2)
x_reshaped

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [126]:
# change the view
z = x.view(1,12)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [127]:
z[:,0] =5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [130]:
#stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim =0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [145]:
x_reshaped.unsqueeze(dim=1),x_reshaped.unsqueeze(dim=1).shape

(tensor([[[[ 5.,  2.],
           [ 3.,  4.],
           [ 5.,  6.]]],
 
 
         [[[ 7.,  8.],
           [ 9., 10.],
           [11., 12.]]]]),
 torch.Size([2, 1, 3, 2]))

In [146]:
x_reshaped = x_reshaped.reshape(2,3,2)
x_reshaped, x_reshaped.shape

(tensor([[[ 5.,  2.],
          [ 3.,  4.],
          [ 5.,  6.]],
 
         [[ 7.,  8.],
          [ 9., 10.],
          [11., 12.]]]),
 torch.Size([2, 3, 2]))

In [148]:
#permute
x_permuted = x_reshaped.permute(1,0,2)
x_permuted, x_permuted.shape

(tensor([[[ 5.,  2.],
          [ 7.,  8.]],
 
         [[ 3.,  4.],
          [ 9., 10.]],
 
         [[ 5.,  6.],
          [11., 12.]]]),
 torch.Size([3, 2, 2]))

In [152]:
x_permuted[0,0,0] = 23
x_permuted, x_reshaped

(tensor([[[23.,  2.],
          [ 7.,  8.]],
 
         [[ 3.,  4.],
          [ 9., 10.]],
 
         [[ 5.,  6.],
          [11., 12.]]]),
 tensor([[[23.,  2.],
          [ 3.,  4.],
          [ 5.,  6.]],
 
         [[ 7.,  8.],
          [ 9., 10.],
          [11., 12.]]]))

In [153]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [154]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [163]:
x[:,:,1]

tensor([[2, 5, 8]])

In [164]:
x[0,0,:]

tensor([1, 2, 3])

In [165]:
x[0,2,2],x[0,:,2]

(tensor(9), tensor([3, 6, 9]))

In [166]:
import torch
import numpy as np

In [169]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [170]:
tensor.dtype

torch.float32

In [175]:
#Randomness
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9244, 0.1804, 0.7540, 0.2438],
        [0.2027, 0.8791, 0.6831, 0.8940],
        [0.5763, 0.0665, 0.6109, 0.9605]])
tensor([[0.6758, 0.2563, 0.0681, 0.7923],
        [0.6502, 0.3600, 0.5995, 0.7832],
        [0.9462, 0.5353, 0.2991, 0.3024]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [176]:
RANDOM_SEED = 42

In [179]:
gen = torch.manual_seed(RANDOM_SEED)

In [188]:
gen = torch.manual_seed(42)
random_tensor_C = torch.rand(3,4, generator = gen)
random_tensor_D = torch.rand(3,4, generator = gen)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [189]:
!nvidia-smi

Thu Jul 25 22:27:46 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.12                 Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   75C    P8              5W /   50W |     494MiB /   4096MiB |     20%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [190]:
# check for gpu access with pytorch
torch.cuda.is_available()

True

In [191]:
# setup device agnostic code
device ="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [192]:
#Count no of Gpus
torch.cuda.device_count()

1

In [ ]:
#Putting tensors and models on GPU
#Create a tensor
tensor_on_gpu = torch.tensor([1,2,3], device)

print(tensor, tensor.device)