In [1]:
import torch
import numpy as np

In [9]:
data =[[1,2],[3,4]]
x_data = torch.tensor(data)

In [10]:
x_data.dtype

torch.int64

In [11]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: {x_ones}")

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random Tensor: {x_rand}")

Ones Tensor: tensor([[1, 1],
        [1, 1]])
Random Tensor: tensor([[0.1937, 0.9211],
        [0.6416, 0.4851]])


In [12]:
shape=(2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor {rand_tensor}")
print(f"Ones Tensor: {ones_tensor}")
print(f"Zeros Tensor: {zeros_tensor}")


Random Tensor tensor([[0.2351, 0.5266, 0.2812],
        [0.6367, 0.6337, 0.3487]])
Ones Tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
tensor = torch.ones(4,4)


In [16]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)
t1, t1.shape

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 torch.Size([4, 12]))

In [17]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out = y3)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [18]:
y3

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [22]:
agg = tensor.sum(dim=1)
agg

tensor([4., 4., 4., 4.])

In [24]:
tensor.add(5),tensor

(tensor([[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [25]:
tensor.add_(5), tensor

(tensor([[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]),
 tensor([[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]))

In [26]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [27]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [31]:
import numpy as np

In [32]:
n = np.ones(5)
t = torch.from_numpy(n)

In [34]:
np.add(n,1, out = n)
print(n)
print(t)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
